### ISSUE TITLE
 ReferenceError: ResizeObserver is not defined. Breaks Jest tests

### ISSUE THREAD

**Issue by IsidroMar95** [ycs77/headlessui-float#10]
- Headless UI Float: v1.6.1
 - Framework: Vue 3

I'm implementing tests to my Tooltip component, but when the test pass, breaks with this error...
how can I mock the ResizeObserver?

![image](https://user-images.githubusercontent.com/23019968/171945642-55caaaab-a11d-4479-9fc5-55ae4a68fb07.png)

**Comment by ycs77** [comment]
see: https://stackoverflow.com/questions/64558062/how-to-mock-resizeobserver-to-work-in-unit-tests-using-react-testing-library
