### ISSUE TITLE
portal connection render for DOM elements

### ISSUE THREAD

**Issue by d90375** [ycs77/headlessui-float#113]
**Is your feature request related to a problem? Please describe.**
Improvement : Performance leak

use case: Table (a lot of cells that use tooltip) 
When we use original `<table> <tr>` (default browser behaviour) element we should use portal otherwise it will overflowed
![image](https://github.com/ycs77/headlessui-float/assets/18696683/d836388e-67ff-4ecf-9c7a-691081ef58ea)
portal property create DOM element for each float element
![image](https://github.com/ycs77/headlessui-float/assets/18696683/e0667fb3-78a8-446a-ae99-e72d52004cb1)

**Describe the solution you'd like**
How it can be improved ? for example: create portal connection to Float only if element show, or create just one portal that can be connect for each Float

**Describe alternatives you've considered**
^_

**Comment by d90375** [comment]
hey @ycs77 do you have any idea how it would be optimised ?

**Comment by ycs77** [comment]
Hi @d90375, sorry I have no current plans to resolve this issue.

I created this package to float the Headless UI component quickly, and non-invasive to the Headless UI, just supported floating the basic usage for the Headless UI example. This change will increase the complexity of this package.  So if you want to use the tooltip, I suggest using [Tippy.js](https://atomiks.github.io/tippyjs/).
