### ISSUE TITLE
Support for @headlessui/react version 2

### ISSUE THREAD

**Issue by PodStuart** [ycs77/headlessui-float#115]
**Is your feature request related to a problem? Please describe.**
Unable to upgrade to @headlessui/react version 2.

**Describe the solution you'd like**
Support for @headlessui/react version 2.

**Describe alternatives you've considered**
Dropping use of @headlessui-float/react.

**Comment by ycs77** [comment]
Hi @PodStuart. Sorry, I can not support the @headlessui/react v2.

Because the @headlessui/react v2 includes the Floating UI, conflict arises in this package, which cannot function normally.

So, I suggest you abandon this package, upgrade to @headlessui/react v2 to use the [`anchor` prop](https://headlessui.com/react/menu) instead of this package, and reference [the example](https://github.com/tailwindlabs/headlessui/blob/7be23e5c7e2e71218cdba405ea4f4aca7924acc8/playgrounds/react/pages/menu/menu-with-transition.tsx) to add the transition for menu or other components.

**Comment by razzeee** [comment]
But you can't do autoplacement with the anchor prop?

I've also migrated some of our projects and they all seem to run fine, as far as I can tell.

**Comment by ycs77** [comment]
@razzeee

> But you can't do autoplacement with the anchor prop?

Although I can do auto-placement, but the `anchor` prop of Headless UI v2 only implements the auto-placement feature, so I can't support the other features of this package.

The usage of FLoating UI APIs with this package and Headless UI v2 is different, I am unable to implement full feature support (like Floating UI options, arrow, portal...) for Headless UI v2, and this package is non-invasive to the Headless UI, if the Headless UI has changed and this package will be affected a lot. So I give up support it. 😅

> I've also migrated some of our projects and they all seem to run fine, as far as I can tell.

If you run fine, continue to do it!

**Comment by scottwillman** [comment]
Well @ycs77 - Let me just say thank you for supporting it while you could!! Much love. It's been a big help to me at missn.com.

**Comment by vincerubinetti** [comment]
Hi there,

It seems like, hopefully, Headless UI v2 should basically make this package obsolete? Unless it doesn't provide as good of access to the underlying Floating UI. And of course, at the moment, v2 is only for React... I desperately hope that they release a Vue v2 as well soon.

Anyway, as such, perhaps you should add a note to the top of the readme like this:

> [!NOTE]  
> [Headless UI](https://headlessui.com/) has [released version 2.0](https://tailwindcss.com/blog/headless-ui-v2#built-in-anchor-positioning) (currently for React only), which builds in anchor positioning with Floating UI, making this package obsolete.

**Comment by ycs77** [comment]
@vincerubinetti done, thanks for your suggestion.
