### ISSUE TITLE
Page scroll up when open first

### ISSUE THREAD

**Issue by vinnygambiny** [ycs77/headlessui-float#118]
**Use Version**
Use version when bugs appear:
 - Headless UI: v1.7.22
 - Headless UI Float: v0.14.0
 - Framework: vue 3.4.0
 - Browser chrome

**Describe the bug**
When I click on the ComboboxButton, the page scroll up. Only happen on the first click. It's don't scroll up completly, but we don't see the ComboboxOptions.

**To Reproduce**

Wrap the Combobox with the Float.
Add some space to add scroll.
On first click on ComboboxButton, the page scroll

**Expected behavior**
The page don't move

**Comment by ycs77** [comment]
Hi, please provide a minimal reproducible example (like github repo, codesandbox, stackblitz...), it is recommended to fork the Headless UI Flaot's [Online Demo](https://headlessui-float.vercel.app/vue/quick-start.html#online-demo) to reproduce.

**Comment by ycs77** [comment]
This issue will be closed because you do not provide a minimal working example. 😅
