### ISSUE TITLE
Will you support HeadlessUI React v2?

### ISSUE THREAD

**Issue by scottwillman** [ycs77/headlessui-float#121]
Big fan of this library, but it will quickly fall out of favor if HeadlessUI proper moves on without it. Do you plan to support v2 or should we look elsewhere?

**Comment by ycs77** [comment]
@scottwillman Sorry, I can not support the @headlessui/react v2.

More infomation see https://github.com/ycs77/headlessui-float/issues/115#issuecomment-2131390528
