### ISSUE TITLE
Vue: Dropdown menu does not close on click outside since 0.14.0 

### ISSUE THREAD

**Issue by dbohn** [ycs77/headlessui-float#122]
**Use Version**
Use version when bugs appear:
 - Headless UI: v1.7.22
 - Headless UI Float: v0.14.0
 - Framework: Vue 3.4.15
 - `@floating-ui/vue`: v1.1.2
 - Browser Edge 127, Firefox 128

**Describe the bug**

We use the `Menu` component to build a dropdown menu together with the `Float` component provided with this package.
We use a custom component for the `MenuItems` component, that is bound using the `as` property of this component, to have the same set of styles across our dropdown containers.

Up until version 0.13.3 of this package, the dropdown would close automatically, when a click outside occured. But since version 0.14.0 the dropdown will not close anymore after opened once.

**To Reproduce**

See the minimal reproduction in this CodeSandbox: https://codesandbox.io/p/sandbox/headlessui-float-reproduction-tnypxw

When clicking on the button "Menu Button" the dropdown will show as expected, but it cannot be dismissed anymore.

When lowering the version of this package to version 0.13.3, the dropdown can be dismissed again. Alternatively, the dismiss behaviour can also be restored by removing the `as` property of the `MenuItems` component.

**Expected behavior**
The dropdown is expected to be closed, when either the menu button is clicked again or the user clicks outside of the dropdown element.

**Comment by ycs77** [comment]
Hi @dbohn, v14.0 has changed the feature of transition, so if you want change back Vue built-in Transition component like v13.x, you must add the `vue-transition` prop of `<Float>`:

```vue
<Menu>
  <Float vue-transition>
    <MenuButton> Menu Button </MenuButton>
    <MenuItems :as="ItemsContainer">
      <MenuItem>
        <button>Entry 1</button>
      </MenuItem>
    </MenuItems>
  </Float>
</Menu>
```
