### ISSUE TITLE
Warning: A props object containing a "key" prop is being spread into JSX

### ISSUE THREAD

**Issue by vigenere23** [ycs77/headlessui-float#126]
**Use Version**
Use version when bugs appear:
 - Headless UI: v1.7.19 (latest v1)
 - Headless UI Float: v0.14.3 (latest)
 - Framework: react v18.2.0 (almost latest v18)
 - `@floating-ui/core`: not directly installed
 - `@floating-ui/dom`: not directly installed
 - Browser : chrome, firefox, probably any (not browser specific)

**Describe the bug**
When rendering the Float component, it warns (as a console.error) that a component with a `key` prop is being rendered using a spread instead of a manual `key={props.key}`.

This as no impact on the behaviour or the functionality of the Menu, but since it's a console error, it breaks our rendering tests, and still should not happen.

**To Reproduce**

Simply go to the [online demo](https://stackblitz.com/github/ycs77/headlessui-float/tree/main/examples/example-react?file=package.json) and open the console.

Else, here is a very minimal example :

```
<Menu>
  <Float>
    <Menu.Button>Click me</Menu.Button>
    <Menu.Items>
      <Menu.Item>Option 1</Menu.Item>
      <Menu.Item>Option 2</Menu.Item>
    </Menu.Items>
  </Float>
</Menu>
```

**Screenshots**

<img width="451" alt="Screenshot 2024-08-28 at 10 58 56" src="https://github.com/user-attachments/assets/5aa838c9-8129-4fa5-bda9-818872c537c0">

**Expected behavior**
No errors in the console.

**Comment by goodallt** [comment]
I just noticed this issue as well

**Comment by ycs77** [comment]
Fixed in v0.14.4

**Comment by goodallt** [comment]
Thank you for the quick fix!! 🙌🎉🍻

**Comment by vigenere23** [comment]
I confirm that it works, thank you very much!
