### ISSUE TITLE
Accept `className` as part of FloatProps

### ISSUE THREAD

**Issue by JesusTheHun** [ycs77/headlessui-float#13]
**Is your feature request related to a problem? Please describe.**

I'm using a combobox that uses all space available.
Right now `Float` renders a blank div by default, meaning that its width will be width of its content. I want the width of the `Float` div to take all the space available.

So right now I have to create a dumb component and pass it to `Float`: 

```tsx
const FullWidthDiv: React.FC = ({children}) => <div className='w-full'>{children}</div>;
<Float as={FullWidthDiv} />
```

It feel like unnecessary work and accepting/passing `className` to the div would be more intuitive. Maybe disable (or trigger a warning) that if `as` is provided because the element itself may not accept `className` as a prop.

**Comment by ycs77** [comment]
Hi @JesusTheHun 

Can you please provide minimal examples (using like github repo, codesandbox, stackblitz..., and suggest can use the Vite & React scaffolding: https://vite.new/react) with the ComboBox component? because I don't know your intention 😅.

**Comment by JesusTheHun** [comment]
Stackblitz : https://stackblitz.com/edit/github-k6mhmk?file=src/components/ExampleComboboxWithAs.tsx

Check the `DummyDiv` at the end of the file. I have to create a dummy div just to add some classes. It would be nice to just pass them to the `Float` component : 

```tsx
<Float className={'w-full'}> ... </Float>
```

**Comment by JesusTheHun** [comment]
No I'm not. 
I just want my option list to be the same width as my button. So I need to tell the float to take all the space available.

**Comment by ycs77** [comment]
You can use this to set the list to be the width same as the button.

First, you have to wrap the `<Float>` with a `<div>` containing the `relative` and the width class, set the `as={Fragment}` prop of `<Float>`, final set the options list and button width to full (`w-full`).

```jsx
import { Fragment } from 'react'

<Listbox>
  <div className="relative w-[260px]">
    <Float placement="bottom" offset={4} as={Fragment}>
      <Listbox.Button className="w-full ...">
        ...
      </Listbox.Button>

      <Listbox.Options className="w-full ...">
        ...
      </Listbox.Options>
    </Float>
  </div>
</Listbox>
```

If you want to set the width as button self width, you can use the `inline-block` for the wrapper:

```jsx
<Listbox>
  <div className="relative inline-block">
    <Float>...</Float>
  </div>
</Listbox>
```

Or wrap a flexbox out fo the `<Listbox>`:

```jsx
<div className="flex items-center">
  <Listbox>
    <div className="relative">
      <Float>...</Float>
    </div>
  </Listbox>
</div>
```

Reference from Headless UI Listbox example: https://headlessui.com/react/listbox

**Comment by JesusTheHun** [comment]
Your example could work, if we didn't circle back to #16 . Using `Fragment` the position is messed up, in my case the position ignores the shift.
