### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')

### ISSUE THREAD

**Issue by mohammadhosseinmoradi** [ycs77/headlessui-float#132]
Headless UI Float break with Next v15 and React v19 and I get this error: `TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')`. I think this error comes from `useOutsideClick` hook.

**Use Version**
 - Headless UI Float v0.15.0
- Next v15.0.1
-  React v19

**To Reproduce**
[https://github.com/mohammadhosseinmoradi/headlessui-float-ReactCurrentDispatcher.git](url)

**Comment by ycs77** [comment]
Sorry, I don't support for React v19 and Next.js v15.

The @headlessui-float/react only supports the Headless UI v1, and the Headless UI v1 just supports React 16 ~ 18, so I can't support React v19.

If you want to use React v19, please upgrade to Headless UI v2, which builds in anchor positioning with Floating UI.
