### ISSUE TITLE
Adaptive width breaks when using portal on a Listbox/Combobox

### ISSUE THREAD

**Issue by wbali** [ycs77/headlessui-float#24]
**Use Version**
Use version when bugs appear:
 - Headless UI: v1.7.2
 - Headless UI Float: v0.9.1
 - Framework: react v18.2.0
 - `@floating-ui/core`: v1.0.0
 - `@floating-ui/dom`: v1.0.0
 -  Chrome

**Describe the bug**
When using the adaptive width with the `portal` option on a Listbox (or Combobox) component the Listbox Options container is too wide.

**To Reproduce**
[https://stackblitz.com/edit/github-uv3nar?file=src/components/ExampleListbox.tsx](https://stackblitz.com/edit/github-uv3nar?file=src/components/ExampleListbox.tsx)

**Comment by ycs77** [comment]
Fixed in v0.10.0
