### ISSUE TITLE
Not working with `@headlessui/vue` v1.7.3 and `vue` >=3.2.34

### ISSUE THREAD

**Issue by ycs77** [ycs77/headlessui-float#28]
**Use Version**
Use version when bugs appear:
 - Headless UI: v1.7.3
 - Headless UI Float: v0.10.0
 - Framework: vue >=3.2.34
 - `@floating-ui/core`: v1.0.0
 - `@floating-ui/dom`: v1.0.0
 - Browser: chrome

**Describe the bug**
Not working

**To Reproduce**
Open example: https://github.com/ycs77/headlessui-float/tree/497f8a1a31570138cc644be70388b42f6baed54a/examples/example-vue
1. remove `yarn.lock`
2. update `package.json`: `"@headlessui/vue": "1.7.3",`
3. update `package.json`: `"vue": "3.2.41",`
4. run `yarn && yarn watch:example:vue`

**Screenshots**
![1665844102439](https://user-images.githubusercontent.com/38133356/195991868-1fdcdd81-26f1-41cf-bca3-d4f6874d0758.jpg)

**Expected behavior**
Working, no print error.

**Comment by empresarrollo** [comment]
FYI, I just installed this (I love it, thanks for your work!), and trying a simple example of with a `<Menu>` and it seems to work OK. I'm on Vue 3.2.41 and HeadlessUI/vue 1.7.4

**Comment by ycs77** [comment]
Fixed on v0.10.1
