### ISSUE TITLE
Support for Virtual Elements

### ISSUE THREAD

**Issue by designbyadrian** [ycs77/headlessui-float#30]
Floating supports [virtual elements](https://floating-ui.com/docs/virtual-elements), which can be used for contextual menus, for example.

How do I achieve this with headlessui-float?

**Comment by ycs77** [comment]
I will consider adding this feature but will have to wait until I have time. 😅

**Comment by ycs77** [comment]
Now support the virtual element in v0.11, can see the docs [Virtual Element](https://headlessui-float.vercel.app/vue/virtual-element.html) to use it.
