### ISSUE TITLE
Cannot read properties of undefined (reading 'body')

### ISSUE THREAD

**Issue by jeffreyvanhees** [ycs77/headlessui-float#32]
**Use Version**
```
"vite": "^3.1.0",
"@headlessui-float/vue": "^0.10.0",
"@headlessui/vue": "^1.7.4",
"vue": "^3.2.45"
```

**Describe the bug**
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'body')` occurs in `getNearestOverflowAncestor()` when opening Listbox.

**To Reproduce**
See: https://stackblitz.com/edit/github-vfx4en-okqi6n?file=src%2Fcomponents%2FExampleListbox.vue to reproduce (open listbox and view console)

**Comment by Frankaus** [comment]
Hi there, I have this bug as well and was about to open the same issue. Did you already resolve it? Thank you.

**Comment by Frankaus** [comment]
By removing `floating-as="template"` the error disappears but there is no styles being applied
