### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'current')

### ISSUE THREAD

**Issue by pkvov** [ycs77/headlessui-float#36]
**Use Version**
Use version when bugs appear:
 - Headless UI: v1.7.4
 - Headless UI Float: v0.10.1
 - Framework: [e.g. vue v3.2.0, react v17.0.2]
 - `@floating-ui/core`: v1.0.0
 - `@floating-ui/dom`: v1.0.0

**Describe the bug**
TypeError: Cannot read properties of undefined (reading 'current')

use with Popover
`<Float placement="bottom-start" flip shift>`

**To Reproduce**

1. react version only in production deployment

**Comment by ycs77** [comment]
Hi @pkvov, Please provide a minimal reproducible example (like github repo, codesandbox, stackblitz...) so I can debug. otherwise, this issue will be closed. 😅
