### ISSUE TITLE
The origin class is based on the initial placement and not the detected one (using flip or autoPlacement)

### ISSUE THREAD

**Issue by VinceBT-BG** [ycs77/headlessui-float#39]
**Use Version**
Use version when bugs appear:
 - Headless UI: v1.7.7
 - Headless UI Float: v0.10.1
 - Framework: [e.g. react v17.0]
 - Browser: chrome

**Describe the bug**
The origin class is based on the initial placement and not the detected one (using flip or autoPlacement)

**To Reproduce**
1. Make a Float with placement `left` at the leftmost side of the screen using `tailwindcssOriginClass` and Tailwind animation
2. Make the float appear
3. It appears on the right but with `transform-right` class

**Screenshots**
![2023-01-18 19 49 33](https://user-images.githubusercontent.com/117643868/213268388-7b89b148-5164-4a72-8cd8-37018d1deb4d.gif)

**Expected behavior**
The popper's transform origin should be changed according to the one resolved

**Comment by ycs77** [comment]
@VinceBT-BG Thanks for the report, now fixed in the v0.11.
