### ISSUE TITLE
Pin arrow to the left

### ISSUE THREAD

**Issue by aarondfrancis** [ycs77/headlessui-float#40]
**Use Version**
 - Headless UI: v1.7.7
 - Headless UI Float: v0.10.1
 - Framework: Vue 3.2.0

**Describe the question**
Thank you for this awesome library! It made integration super easy, I really appreciate it.

Is there a way to pin the arrow to the left? Right now the parent element is changing size and so the arrow is changing size, and I'd prefer to keep it pinned on the left. See the video below.

Thanks again!

**Screenshots**

https://user-images.githubusercontent.com/881931/213461634-465f12a4-e9b5-4b12-9700-9149df195758.mp4

**Comment by ycs77** [comment]
Hi @aarondfrancis, can you try to see if using !important left 0 on arrow can solve it?

```html
<FloatArrow class="absolute !left-0 ..." />
```

It's not the best solution, but I'll be think of a better on while.

**Comment by aarondfrancis** [comment]
Brilliant solution! Thank you 😄
