### ISSUE TITLE
Add a prop to disable pointer events inside floating element

### ISSUE THREAD

**Issue by VinceBT-BG** [ycs77/headlessui-float#41]
**Is your feature request related to a problem? Please describe.**
When using the component as a tooltip, you sometimes want to disable hovering completely but this issue happens:
![2023-01-23 11 41 05](https://user-images.githubusercontent.com/117643868/214019989-0d71701c-4c9d-42a7-8792-9df05206e480.gif)
 This is because there is no possibility to pass props to the wrapping div of the floating element

**Describe the solution you'd like**
Either a prop disabling pointer events on the div, either being able to pass anything to the div, like a className or a style prop, that is added to it

**Comment by ycs77** [comment]
Hi @VinceBT-BG, sorry I don't quite understand what you mean 😅, can you provide a simple example (like github repo, codesandbox, stackblitz...) to reproduce the above gif? (have your expectations and now actual)

**Comment by VinceBT-BG** [comment]
Sorry if I was unclear, my point was to add a way to pass custom `style` or `classname` to the floating container here https://github.com/ycs77/headlessui-float/blob/main/packages/react/src/float.tsx#L308, to pass for example `pointer-events: none` to completely ignore hover events and also add more possibility to customize

**Comment by ycs77** [comment]
You can use `floatingAs={React.Fragment}` to have full floating element control:

```jsx
import React from 'react'

<Float floatingAs={React.Fragment}>
  <Listbox.Button>
    ...
  </Listbox.Button>

  {/* now no <div> wrapper, you have full floating element control */}
  <Listbox.Options style="pointer-events: ...">
    ...
  </Listbox.Options>
</Float>
```

code source from:

https://github.com/ycs77/headlessui-float/blob/ae53a5a4bd915e64684abddc3aef61b4151a3a7e/packages/react/src/float.tsx#L355-L357

Does this solve your problem?

**Comment by ycs77** [comment]
Turn off `transform` to switch to `top/left` properties for positioning can solve:

```jsx
<Float transform={false}>
```

**Comment by VinceBT-BG** [comment]
<img width="164" alt="Capture d’écran 2023-02-03 à 18 18 51" src="https://user-images.githubusercontent.com/117643868/216666369-6975faa3-69f5-4da9-8e2a-a04c7fd62d54.png">

This is how it renders without `transform={false}`

**Comment by ycs77** [comment]
Or you can use custom forward element:

```jsx
const FloatingWrapper = React.forwardRef(({ children, ...otherProps }, ref) => {
  // Add any your custom attributes or styles
  return <div {...otherProps} ref={ref}>{children}</div>
})

<Float floatingAs={FloatingWrapper}>
```

**Comment by VinceBT-BG** [comment]
With `floatingAs={FloatingWrapper}`
<img width="977" alt="Capture d’écran 2023-02-06 à 12 09 43" src="https://user-images.githubusercontent.com/117643868/216956651-a3e79013-b9af-4ba5-8d5d-4fcbec6d9010.png">
![2023-02-06 12 09 12](https://user-images.githubusercontent.com/117643868/216956688-3da495cf-3f8d-4b12-9743-d8c7333daee6.gif)

With just `floatingAs="div"`
![2023-02-06 12 10 44](https://user-images.githubusercontent.com/117643868/216956921-bef7d335-f923-45b8-afb6-d351a67d383c.gif)

**Comment by ycs77** [comment]
@VinceBT-BG If you want to make the tooltip I suggest using Tippy.js (Tippy.js for React: https://github.com/atomiks/tippyjs-react), I think the Headless UI Float is not to create the tooltip😅

But, if you still using Headless UI Float, can you provide your current tooltip code? I can be easy to debug.

**Comment by ycs77** [comment]
Hi @VinceBT-BG, did your question get resolved? If so I will close this issue, please open a new one if you have any questions.

**Comment by VinceBT-BG** [comment]
I tried everything and did not manage to make it work, the simplest solution would be to add the basic possibility to forward style or classname to the element I provided

**Comment by ycs77** [comment]
@VinceBT-BG I have added a feature to v0.11, you can add any attribute to the floating element at will, see [Composable Mode](https://headlessui-float.vercel.app/react/composable-mode.html), you can update to v0.11 and use it.

And here has a tooltip example:

```jsx
import { useState } from 'react'
import { Float } from '@headlessui-float/react'

export default function ExampleTooltip() {
  const [show, setShow] = useState(false)
  return (
    <Float
      show={show}
      placement="bottom"
      arrow
      enter="transition duration-[1s] ease-out"
      enterFrom="scale-95 opacity-0"
      enterTo="scale-100 opacity-100"
      leave="transition duration-[0.5s] ease-in"
      leaveFrom="scale-100 opacity-100"
      leaveTo="scale-95 opacity-0"
      tailwindcssOriginClass
      composable
    >
      <Float.Reference>
        <div
          className="inline-block"
          onMouseEnter={() => setShow(true)}
          onMouseLeave={() => setShow(false)}
        >
          Hover me!
        </div>
      </Float.Reference>

      <Float.Content className="pointer-events-none">
        <div className="relative px-2 py-1 bg-gray-800 text-white rounded">
          <Float.Arrow className="absolute bg-gray-800 w-5 h-5 rotate-45" />
          <div className="relative">
            I am a tooltip!
          </div>
        </div>
      </Float.Content>
    </Float>
  )
}
```

If you have other questions, open a new issue and attach your sample code or minimally reproducible GitHub project. [Online demo](https://headlessui-float.vercel.app/react/quick-start.html#online-demo) provided more `<Flaot>` examples.
