### ISSUE TITLE
Shift parameter does not prevent the arrow from sticking out of the container

### ISSUE THREAD

**Issue by VinceBT-BG** [ycs77/headlessui-float#48]
**Use Version**
Use version when bugs appear:
 - Headless UI: v1.7.5
 - Headless UI Float: v0.11.0
 - Framework: react v18.0
 - `@floating-ui/core`: v1.0.0
 - `@floating-ui/dom`: v1.0.0
 - Browser chrome

**Describe the bug**
When using `shift` with a value > 0, the arrow sticks out of the box

**To Reproduce**
1. Go to https://stackblitz.com/edit/github-aburrl?file=src/pages/arrow.jsx
2. Click on Arrow options menu
3. Scroll to the right while the menu is open

**Screenshots**
![2023-03-13 14 24 18](https://user-images.githubusercontent.com/117643868/224715100-a6fdfd8b-c56d-4888-9152-ee4609ce3b7d.gif)

**Expected behavior**
The arrow should have a minimal `left` to it does not stick out from the container, depending on its size

**Comment by ycs77** [comment]
@VinceBT-BG The example is fixed, thanks for the report😊

You can using `arrow={5}` to add `5px` padding from the arrow to the float container:

```jsx
<Float shift={5} placement="bottom-start" offset={12} flip arrow={5}>
```

Also if setting the big arrow and must be setting the big padding.
