### ISSUE TITLE
Any example for animating a popover opening from the other side ?

### ISSUE THREAD

**Issue by VinceBT-BG** [ycs77/headlessui-float#49]
**Use Version**
 - Headless UI: v1.7.5
 - Headless UI Float: v0.11.0
 - Framework: react v18.0

**Describe the question**
Do you have any example on how to make the transition from a popover come from the bottom towards top when the placement has been changed ?

**Screenshots**
Screenshot is from the demo page, adding a margin top to the popover button until it is stuck at the bottom of the screen
![2023-03-16 15 06 16](https://user-images.githubusercontent.com/117643868/225642725-a6d18135-05cf-4e67-9289-479c9e04dcae.gif)

**Comment by ycs77** [comment]
Hi @VinceBT-BG, this problem involves the use of `<Transition>` of Headless UI. Currently, I have asked this problem in https://github.com/tailwindlabs/headlessui/discussions/2432, and I need to wait for the reply there to solve it.

**Comment by ycs77** [comment]
Regarding this response, please refer to #57
