### ISSUE TITLE
Passing props to React.Fragments

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [ycs77/headlessui-float#50]
**Use Version**
@headlessui-float/react: "^0.11.0",

**Describe the bug**
When using the following popover setup, the package is rendering React.Fragment elements, and attempting to pass styles to them leading to console warnings:

`Warning: Invalid prop `style` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.`

```
<Popover>
  {({ open }) => (
    <Float
	 placement="bottom-end"
	 offset={15}
	 arrow={5}
	 transform={false}
	 floatingAs={Fragment}
	 enter="transition ease-out duration-100"
	 enterFrom="transform opacity-0 scale-95"
	 enterTo="transform opacity-100 scale-100"
	 leave="transition ease-in duration-75"
	 leaveFrom="transform opacity-100 scale-100"
	 leaveTo="transform opacity-0 scale-95"
	 tailwindcssOriginClass
     >
	  <Popover.Button as={PrimaryButton} className="uppercase font-bold" size={ButtonSize.M} icon={ArrowUpRightIcon}>
		 <span className="sr-only">{open ? 'Open' : 'Close'} create menu</span>
			 Get Started
		 </Popover.Button>

		 <Popover.Panel className="bg-blue rounded-3xl shadow-lg p-8 text-white">
			 <Float.Arrow as="div" className="absolute bg-blue w-5 h-5 rotate-45" />

			 <div className="relative">
			 	{...}
			 </div>
		 </Popover.Panel>
	 </Float>
	 )}
 </Popover>
```

**Comment by ycs77** [comment]
Hi @TheRealFlyingCoder, I can't reproduce this bug, please provide a minimally reproducible repo using GitHub or stackblitz, [Online demo](https://headlessui-float.vercel.app/react/quick-start.html#online-demo) provided the `<Float>` stackblitz examples.

**Comment by TheRealFlyingCoder** [comment]
> Hi @TheRealFlyingCoder, I can't reproduce this bug, please provide a minimally reproducible repo using GitHub or stackblitz, [Online demo](https://headlessui-float.vercel.app/react/quick-start.html#online-demo) provided the `<Float>` stackblitz examples.

Weird, let me debug it a bit more and i'll get back to you with an example!

**Comment by TheRealFlyingCoder** [comment]
@ycs77 I should have picked this up straight away before raising the ticket:

`floatingAs={Fragment}`

That was the problem ^ switching to a div solved it
