### ISSUE TITLE
Hide events being emitter before each Show event

### ISSUE THREAD

**Issue by igorvukic** [ycs77/headlessui-float#51]
**Use Version**
Use version when bugs appear:
 - Headless UI: v1.7.12
 - Headless UI Float: v0.11.0
 - Framework: vue v3.2.47
 - `@floating-ui/core`: v1.0.0
 - `@floating-ui/dom`: v1.0.0
 - Browser chrome

**Describe the bug**
`hide` event is emitted before every `show` event

**To Reproduce**
1) Add @show and @hide events and console.log once they occur. You will notice that before each opening `hide` event is emitted 

**Screenshots**
![image](https://user-images.githubusercontent.com/25299683/228790708-d1ae1fb7-a8b7-48bc-91b7-2f0ebc7af753.png)

**Expected behavior**
`hide` event should be only emitted on closing and not before opening

**Comment by igorvukic** [comment]
Here is a screenshoot of event listeners: 
![image](https://user-images.githubusercontent.com/25299683/228791344-b21034d2-0c13-4604-8685-fca03ab380e7.png)

**Comment by ycs77** [comment]
@igorvukic Thanks~
