### ISSUE TITLE
Page jump to the top on popover open, when using `focus: true`

### ISSUE THREAD

**Issue by wa0x6e** [ycs77/headlessui-float#53]
**Use Version**
Use version when bugs appear:
- "@headlessui-float/vue": "*",
- "@headlessui/vue": "^1.7.4",
- "tailwindcss": "^3.0.23",
- "vue": "^3.2.47",

**Describe the bug**
With the popover component, adding the `:focus="true"` prop to the `PopoverPanel` will make the page jump to the top, when clicking on the popover button.

**To Reproduce**

1. Go to https://stackblitz.com/edit/github-dl2yea?file=src/pages/popover.vue
2. Scroll down to the popover button
3. Click on the button
5. See error (the popover do open, but the page scroll back to the top)

Alternatively, you can also reproduce this error by just editing the official stackblitz demo, by adding `:focus="true"` to the popoverPanel, and adding some margin to the page to push the popover button lower in the page.

**Expected behavior**
The page should not scroll, on popover open. (this is the case when using the popover without the `Float` wrapper)

**Comment by ycs77** [comment]
I have checked this, and I don’t plan to solve it. But you can follow the under steps to automatically focus in `<PopoverPanel>`.

---

You can use the `<FocusTrap>` component of Headless UI instead to automatically focus after opening:

```html
<template>
  <!-- remove the `:focus="true"` -->
  <PopoverPanel ...>
    <FloatArrow ... />
    <!-- add <FocusTrap> component -->
    <FocusTrap>
      <div class="relative h-full bg-white p-3 text-rose-500 rounded-md">
        <a href="#">Test</a>
        <a href="#">Test</a>
        <a href="#">Test</a>
        <a href="#">Test</a>
        <a href="#">Test</a>
      </div>
    </FocusTrap>
    <!-- add <FocusTrap> component -->
  </PopoverPanel>
</template>

<script setup>
import { Popover, PopoverButton, PopoverPanel, FocusTrap } from '@headlessui/vue'
</script>
```

`<FocusTrap>` is a Headless UI component that can automatically lock the focus in it, but it is not disclosed in the documentation.
