### ISSUE TITLE
Transitions don't work in composable mode

### ISSUE THREAD

**Issue by klaemo** [ycs77/headlessui-float#55]
Hey there 👋 

**Use Version**
Use version when bugs appear:
 - Headless UI: v1.7.13
 - Headless UI Float: v0.11.1
 - Framework: vue v3.2.47
 - `@floating-ui/core`: v1.2.6
 - `@floating-ui/dom`: v1.2.6
 - Browser: all

**Describe the bug**
Transitions don't work when using composable mode.
I added the transition classes like in the [docs](https://headlessui-float.vercel.app/vue/transition.html), but in combination with `<Float composable>`. Everything works, but the `PopoverPanel` (in my case) doesn't transition. It appears without transition.

**To Reproduce**
Check out the popover demo here: https://stackblitz.com/edit/github-84nbbq?file=src/pages/popover.vue

**Expected behavior**
The `PopoverPanel` etc. uses transition when they are specified like in the [docs](https://headlessui-float.vercel.app/vue/transition.html) even in composable mode.

Thank you for your work on this package :)

**Comment by ycs77** [comment]
Fixed on v0.11.2

**Comment by klaemo** [comment]
Thank you so much! 🎉
