### ISSUE TITLE
Issue with animation when using flip

### ISSUE THREAD

**Issue by VinceBT-BG** [ycs77/headlessui-float#57]
**Use Version**
 - Headless UI: v1.7.5
 - Headless UI Float: v0.11.1
 - Framework: react
 - `@floating-ui/core`: v1.0.0
 - `@floating-ui/dom`: v1.0.0
 - Browser chrome

**Describe the bug**

Flip has a weird behavior if using transitions

**To Reproduce**

1. Use `flip` attribute
2. Use transition origin for a menu popup for example
3. Make it so the menu has no space to open
4. The first time it opens, it will open like it came from the other side
5. The following times it will open normally

I saved the blitz here: https://stackblitz.com/edit/github-avrwwh?file=src/pages/transition.jsx
Go to Transition and click the button

You can see the menu opens from the top left when it has space to open, then I scroll and I press it again, now it opens from the top left one last time before opening from the bottom left after that

**Screenshots**
![2023-04-29 23 48 59](https://user-images.githubusercontent.com/117643868/235325549-b024efd7-8007-4da6-90a8-c3d352085c36.gif)

**Expected behavior**
The block animates from the right spot

**Comment by ycs77** [comment]
Hi @VinceBT-BG, This issue is the same as #49, we need to wait for Headless UI to solve it, I have raised this problem at https://github.com/tailwindlabs/headlessui/discussions/2432, and I need to wait for the reply there.

**Comment by VinceBT-BG** [comment]
Can we do something by using a force re-rendering by using a `key={placement}` on the `Transition` for example ?

**Comment by VinceBT-BG** [comment]
@ycs77 I think I achieved it using the `key` prop : https://codesandbox.io/s/naughty-pare-14ty2i?file=/src/App.js

**Comment by VinceBT-BG** [comment]
What is the status ? I see you got an answer on https://github.com/tailwindlabs/headlessui/issues/2550

**Comment by ycs77** [comment]
Now I'm looking for a solution.

**Comment by VinceBT-BG** [comment]
Why not get out of Headless UI's transition (that has bugs btw when you spam open/hide an entering/hiding animation) and use something such as https://reactcommunity.org/react-transition-group/transition ? That's what I use in local and I have no issues
