### ISSUE TITLE
height

### ISSUE THREAD

**Issue by ahoyahoy** [ycs77/headlessui-float#67]
Can you please implement size() middleware or something to control max height dropdowm menu inside portal?

**Comment by ycs77** [comment]
Hi @ahoyahoy, I currently do not plan to implement the feature of `size()`. I suggest you can directly use Floating UI to implement it. On the one hand, I am not using this function myself. On the other hand, this function is more complex, and I do not know how it will affect the current package. You can implement your function more freely by using Floating UI directly.

Thank you for your understanding.
