### ISSUE TITLE
`onHide` is called every time the component is rendered

### ISSUE THREAD

**Issue by JesusTheHun** [ycs77/headlessui-float#68]
**Use Version**

 - Headless UI: v1.7.5
 - Headless UI Float: v0.11.2
 - Framework: [e.g. vue v3.2.0, react v18.0]
 - `@floating-ui/core`: v1.0.0
 - `@floating-ui/dom`: v1.0.0
 - Browser : chrome, safari

**Describe the bug**
The `onHide` callback is called every time the component is rendered instead of when the dropdown is closed.

**To Reproduce**
https://stackblitz.com/edit/github-tvfv3k?file=src%2Fpages%2Fcombobox.tsx

0. Open your browser's console
1. Go to the Floating Combobox
2. Type something in the input
3. See the logs in the console, showing the calback has been called several time

**Expected behavior**
`onHide` should be only called when the dropdown is closed

**Comment by JesusTheHun** [comment]
After some investigations, `v0.10.1` was working properly. The bug has been introduced by `v0.11.0`

**Comment by senasi** [comment]
This is also true for `onShow` handler, which is called on each render. Even if you set `show={true}` directly to `Float` component, the handler will be called every time.

**Comment by ycs77** [comment]
Fixed on v0.11.3
