### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by G100my** [ycs77/headlessui-float#73]
**Use Version**
Use version when question appear:
- Headless UI: ^1.6.1
 - Headless UI Float: v0.11.2
 - Framework: vue^3.2.38
 - `@floating-ui/core`: v1.0.0
 - `@floating-ui/dom`: v1.0.0
 - NodeJs, `vue-tsc --noEmit -p tsconfig.vitest.json --composite false`

**Describe the question**
```
error TS7016: Could not find a declaration file for module '@headlessui-float/vue'. '....../node_modules/@headlessui-float/vue/dist/headlessui-float.mjs' implicitly has an 'any' type.
  There are types at '...../node_modules/@headlessui-float/vue/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@headlessui-float/vue' library may need to update its package.json or typings.
```
I'm not sure if it's because I placed @headlessui-float/vue in peerDependencies, or if it's due to configuration issues with the monorepo structure, or perhaps it's related to the npm or Node.js versions. TypeScript can indeed find the declaration file for @headlessui-float/vue, but it complains that the package doesn't export the declaration file. I tried moving the package.types to exports['.'], and it it worked correctly.
I tried creating a new project to reproduce the issue, but everything seems to be working fine. 🤣

我不確定是不是因為我把 @headlessui-float/vue 放在 peerDependencies 造成的，或者是因為 monorepo 架構的設定問題，又或者是 npm、node 版本所致。typescript 確實可以找到 @headlessui-float/vue 的 declaration file，但會說 package 沒有把 declaration file export 出來。我嘗試把 package.types 移到 exports['.'] 下面就正常了。
有嘗試開新專案要重現，但一切正常...

**Comment by ycs77** [comment]
哈囉 @G100my

如果你方便的話，可以提供一下的一些資訊，我在有空時會調查看看。

### 1. 套件管理器跟版本

npm/yarn/pnpm 及版本號

### 2. 根據以下步驟建立最小重現專案

1. 將現在有問題的專案在本地複製一份

**Comment by ycs77** [comment]
由於缺乏足夠的資訊，我先暫時關閉該 Issue，請根據以上步驟提供 **最小重現專案** 以重新開啟 Issue，謝謝。

> 關於需要提供 最小重現專案 的原因可以參考文章：[「请提供最小重现」](https://antfu.me/posts/why-reproductions-are-required-zh)
