### ISSUE TITLE
Make a mode where the transform origin is based on the arrow position

### ISSUE THREAD

**Issue by VinceBT-BG** [ycs77/headlessui-float#74]
Could we implement a solution like [this](https://floating-ui.com/docs/floatingarrow#scale-transforms) to make it so the transform origin is set at the arrow tip ? It looks less weird than using tailwind origin classes

Example from the demo:

![2023-08-08 17 02 00](https://github.com/ycs77/headlessui-float/assets/117643868/f60fd022-9c75-4f0a-a59a-48bd8540ac96)

**Comment by ycs77** [comment]
@VinceBT-BG Sorry, I can't add this feature because the main reason is that the Vue version of Floating UI is not supported (this package I want to implement the same feature for React and Vue both).

If you want to use it please directly copy that Example to use.
