### ISSUE TITLE
Can't make Vue dropdown options stick to the Combobox width

### ISSUE THREAD

**Issue by cxammar** [ycs77/headlessui-float#75]
**Describe the bug**
I'm unable to make the combobox options stick to the Combobox max width and break the overflow (float) on the parent container at the same time in Vue 3.

**To Reproduce**
Please refer to this stackblitz https://stackblitz.com/edit/github-qtnwz4

![image](https://github.com/ycs77/headlessui-float/assets/11465431/ca7e33c2-d529-4bcf-875a-8b1a9ae43a61)

![image](https://github.com/ycs77/headlessui-float/assets/11465431/a799fc93-3143-4cbc-a17e-97c0eeee2336)

**Comment by ycs77** [comment]
You can remove the `overflow-hidden` class to fix this:

```diff
        <PopoverPanel
          class="absolute right-0 z-10 mt-3 flex w-screen max-w-max"
        >
          <div
            class="
              w-screen
              max-w-md
              flex-auto
-             overflow-hidden
              rounded-md
              border border-gray-300
              bg-white
              text-sm
              shadow-xl
              ring-2 ring-gray-900/5
            "
          >
            <div class="flex flex-col p-5 space-y-5">
              <OverflowableCombobox
                label="Tipo de cita"
                name="actuationTitle"
                :items="items"
              />
            </div>
          </div>
        </PopoverPanel>
```
