### ISSUE TITLE
`hide()` feature of Floating UI

### ISSUE THREAD

**Issue by rhryhorenko** [ycs77/headlessui-float#88]
We can pass `hide` as a prop to the `<Float/>` component. But, according to [the floating UI Documentation](https://floating-ui.com/docs/hide) the hide() middleware is a data provider. So currently we have no way to get this data, consequently, we cannot hide the floating element after its reference is hidden.

**Comment by ycs77** [comment]
I think this is a feature request.

I currently do not fully implement the `hide()` feature, if I have the time will be to check it.

**Comment by ycs77** [comment]
Released v0.13, see the docs https://headlessui-float.vercel.app/react/floatingui-options.html#hide for more information of hide usage.
