### ISSUE TITLE
With Two Portalled components, neither work

### ISSUE THREAD

**Issue by JohnCampionJr** [ycs77/headlessui-float#89]
**Use Version**
Use version when bugs appear:
 - Headless UI: v1.7.5
 - Headless UI Float: v0.11.4
 - Framework: vue v3.3.0
 - Browser: all

**Describe the bug**
If I have two portalled floating elements, neither work.  It seems the Float is shared across all components

**Expected behavior**
They should work :)

**Comment by ycs77** [comment]
Hi, please provide a minimal reproducible example (like github repo, codesandbox, stackblitz...), it is recommended to fork the Headless UI Flaot's [Online Demo](https://headlessui-float.vercel.app/vue/quick-start.html#online-demo) to reproduce.

**Comment by JohnCampionJr** [comment]
I failed to make a repro - There must be something else conflicting with my project.   I'll re-open if I figure out what it is

**Comment by JohnCampionJr** [comment]
Update for anyone else who encounters this - it is caused by Nuxt SSR.  If I disable SSR or set these components in a ClientOnly wrapper, they work fine.

Not sure why it didn't dawn on me that SSR would break portalling, but it makes sense :)
