### ISSUE TITLE
Browser scrolls up when opening a listbox

### ISSUE THREAD

**Issue by piotrjoniec** [ycs77/headlessui-float#99]
**Version**
@headlessui-float/vue: 0.13.1

**Describe the bug**
The browser scrolls up when opening a listbox. 

https://github.com/ycs77/headlessui-float/assets/7397131/a6de2d6a-5f4d-4ab4-ae79-b61f79255e64

**To Reproduce**
https://stackblitz.com/edit/github-tg6qrz?file=src%2Fpages%2Flistbox.vue

After opening the listbox, my browser (Chrome 121.0.6167.140) scrolls up about 400px. This only happens when opening the listbox for the first time.

When testing the same example on version 0.13.0 of headlessui-float, this problem does not occur.

**Comment by adamwhp** [comment]
I am experiencing the same bug that @piotrjoniec has reported (scrolls to the top of the page when opening the listbox). However, for now, I was able to get it working on 0.13.1 by setting `:unmount="false"` on the `ListboxOptions` component.

**Comment by ycs77** [comment]
Fixed on v0.13.2
